const DIMENSION_UNSPECIFIED = 0;
const DIMENSION_TEMPORAL = 1;
const DIMENSION_VOLTAGE = 2;
const DIMENSION_FREQUENCY = 3;

export default {
    DIMENSION_UNSPECIFIED,
    DIMENSION_TEMPORAL,
    DIMENSION_VOLTAGE,
    DIMENSION_FREQUENCY
};