const DIMENSION_UNSPECIFIED = 0;
const DIMENSION_TEMPORAL = 1;
const VOLTAGE = 2;
const DIMENSION_FREQUENCY = 3;
const DIMENSION_DATASTORAGE = 4;

export default {
    DIMENSION_UNSPECIFIED,
    DIMENSION_TEMPORAL,
    VOLTAGE,
    DIMENSION_FREQUENCY,
    DIMENSION_DATASTORAGE
};